In [1]:
from Jumpit_Crawling_Functions import *

In [2]:
data = crawlingDetailPage()

Loading: 1page [00:00, 10.34page/s]
Loading: 1page [00:00, 12.80page/s]
Loading: 1page [00:00, 13.23page/s]
Loading: 1page [00:00, 12.41page/s]
Loading: 1page [00:00, 12.72page/s]
Loading: 1page [00:00, 13.41page/s]
Loading: 1page [00:00,  9.93page/s]
Loading: 1page [00:00, 12.17page/s]
Loading: 1page [00:00, 12.33page/s]
Loading: 1page [00:00, 11.81page/s]
Loading: 1page [00:00, 12.02page/s]
Loading: 1page [00:00, 12.18page/s]
Loading: 1page [00:00,  7.26page/s]
Loading: 1page [00:00, 11.48page/s]
Loading: 1page [00:00, 12.47page/s]
Loading: 1page [00:00, 11.81page/s]
Loading: 1page [00:00, 11.53page/s]
Loading: 1page [00:00, 10.74page/s]
Loading: 1page [00:00, 10.79page/s]
Loading: 1page [00:00, 12.04page/s]
Loading: 1page [00:00, 11.81page/s]
Loading: 1page [00:00, 11.82page/s]
Loading: 1page [00:00, 11.04page/s]
Loading: 1page [00:00, 11.16page/s]
Loading: 1page [00:00, 10.08page/s]
Loading: 1page [00:00, 12.18page/s]
Loading: 1page [00:00, 10.74page/s]
Loading: 1page [00:00, 10.29page/s]
Loading: 1page [00:00, 11.49page/s]
Loading: 1page [00:00, 10.67page/s]
Loading: 1page [00:00, 11.28page/s]
Loading: 1page [00:00, 10.52page/s]
Loading: 1page [00:00, 11.75page/s]
Loading: 1page [00:00, 11.69page/s]
Loading: 1page [00:00, 10.46page/s]
Loading: 1page [00:00, 11.89page/s]
Loading: 1page [00:00, 12.11page/s]
Loading: 1page [00:00, 11.96page/s]
Loading: 1page [00:00, 11.74page/s]
Loading: 1page [00:00, 12.41page/s]
Loading: 1page [00:00, 11.28page/s]
Loading: 1page [00:00, 11.55page/s]
Loading: 1page [00:00, 11.35page/s]
Loading: 1page [00:00, 12.49page/s]
Loading: 1page [00:00, 10.85page/s]
Loading: 1page [00:00,  9.99page/s]
Loading: 1page [00:00, 11.28page/s]
Loading: 1page [00:00,  9.75page/s]
Loading: 1page [00:00, 10.14page/s]
Loading: 1page [00:00, 11.54page/s]
Loading: 1page [00:00, 11.69page/s]
Loading: 1page [00:00, 10.67page/s]
Loading: 1page [00:00,  9.03page/s]
Loading: 1page [00:00, 10.74page/s]
Loading: 1page [00:00, 10.30page/s]
Loading: 1page [00:00, 10.08page/s]
Loading: 1page [00:00, 11.21page/s]
Loading: 1page [00:00,  9.94page/s]
Loading: 1page [00:00, 10.29page/s]
Loading: 1page [00:00, 11.75page/s]
Loading: 1page [00:00, 11.28page/s]
Loading: 1page [00:00, 10.40page/s]
Loading: 1page [00:00, 10.74page/s]
Loading: 1page [00:00, 10.24page/s]
Loading: 1page [00:00, 10.36page/s]
Loading: 1page [00:00, 10.69page/s]
Loading: 1page [00:00, 12.10page/s]
Loading: 1page [00:00, 10.97page/s]
Loading: 1page [00:00, 10.97page/s]
Loading: 1page [00:00, 10.79page/s]
Loading: 1page [00:00,  9.98page/s]
Loading: 1page [00:00, 11.04page/s]
Loading: 1page [00:00, 10.29page/s]
Loading: 1page [00:00, 11.09page/s]
Loading: 1page [00:00,  9.42page/s]
Loading: 1page [00:00, 10.63page/s]
Loading: 1page [00:00, 10.80page/s]
Loading: 1page [00:00, 10.40page/s]
Loading: 1page [00:00, 11.29page/s]
Loading: 1page [00:00, 11.09page/s]
Loading: 1page [00:00, 11.16page/s]
Loading: 1page [00:00, 10.86page/s]
Loading: 1page [00:00, 10.46page/s]
Loading: 1page [00:00, 10.74page/s]
Loading: 1page [00:00, 10.62page/s]
Loading: 1page [00:00,  8.80page/s]
Loading: 1page [00:00, 10.63page/s]
Loading: 1page [00:00, 10.86page/s]
Loading: 1page [00:00, 17.48page/s]

모든 페이지 정보를 가져 왔습니다
상세 페이지 49679 : https://jumpit.saramin.co.kr/position/49678
상세 페이지 48942 : https://jumpit.saramin.co.kr/position/48941
상세 페이지 49282 : https://jumpit.saramin.co.kr/position/49281
상세 페이지 49578 : https://jumpit.saramin.co.kr/position/49577
상세 페이지 48391 : https://jumpit.saramin.co.kr/position/48390
상세 페이지 48886 : https://jumpit.saramin.co.kr/position/48885
상세 페이지 49617 : https://jumpit.saramin.co.kr/position/49616
상세 페이지 49102 : https://jumpit.saramin.co.kr/position/49101
상세 페이지 49208 : https://jumpit.saramin.co.kr/position/49207
상세 페이지 49681 : https://jumpit.saramin.co.kr/position/49680
상세 페이지 49464 : https://jumpit.saramin.co.kr/position/49463
상세 페이지 48941 : https://jumpit.saramin.co.kr/position/48940
상세 페이지 49028 : https://jumpit.saramin.co.kr/position/49027
상세 페이지 47833 : https://jumpit.saramin.co.kr/position/47832
상세 페이지 49437 : https://jumpit.saramin.co.kr/position/49436
상세 페이지 49890 : https://jumpit.saramin.co.kr/position/49889
상세 페이지 49230 : https://jumpit.saramin.co.kr/position/49229
상세 페이지 49210 : https://jumpit.saramin.co.kr/position/49209
상세 페이지 49085 : https://jumpit.saramin.co.kr/position/49084
상세 페이지 49050 : https://jumpit.saramin.co.kr/position/49049
상세 페이지 49843 : https://jumpit.saramin.co.kr/position/49842
상세 페이지 49466 : https://jumpit.saramin.co.kr/position/49465
상세 페이지 49680 : https://jumpit.saramin.co.kr/position/49679
상세 페이지 49211 : https://jumpit.saramin.co.kr/position/49210
상세 페이지 49358 : https://jumpit.saramin.co.kr/position/49357
상세 페이지 49687 : https://jumpit.saramin.co.kr/position/49686
상세 페이지 49595 : https://jumpit.saramin.co.kr/position/49594
상세 페이지 49155 : https://jumpit.saramin.co.kr/position/49154
상세 페이지 49465 : https://jumpit.saramin.co.kr/position/49464
상세 페이지 50005 : https://jumpit.saramin.co.kr/position/50004
상세 페이지 49553 : https://jumpit.saramin.co.kr/position/49552
상세 페이지 49289 : https://jumpit.saramin.co.kr/position/49288
상세 페이지 49646 : https://jumpit.saramin.co.kr/position/49645
상세 페이지 49761 : https://jumpit.saramin.co.kr/position/49760
상세 페이지 49720 : https://jumpit.saramin.co.kr/position/49719
상세 페이지 49371 : https://jumpit.saramin.co.kr/position/49370
상세 페이지 50156 : https://jumpit.saramin.co.kr/position/50155
상세 페이지 49152 : https://jumpit.saramin.co.kr/position/49151
상세 페이지 49285 : https://jumpit.saramin.co.kr/position/49284
상세 페이지 50494 : https://jumpit.saramin.co.kr/position/50493
상세 페이지 50493 : https://jumpit.saramin.co.kr/position/50492
상세 페이지 49376 : https://jumpit.saramin.co.kr/position/49375
상세 페이지 49648 : https://jumpit.saramin.co.kr/position/49647
상세 페이지 49790 : https://jumpit.saramin.co.kr/position/49789
상세 페이지 50257 : https://jumpit.saramin.co.kr/position/50256
상세 페이지 50261 : https://jumpit.saramin.co.kr/position/50260
상세 페이지 50154 : https://jumpit.saramin.co.kr/position/50153
상세 페이지 50152 : https://jumpit.saramin.co.kr/position/50151
상세 페이지 50323 : https://jumpit.saramin.co.kr/position/50322
상세 페이지 49242 : https://jumpit.saramin.co.kr/position/49241
상세 페이지 50488 : https://jumpit.saramin.co.kr/position/50487
상세 페이지 49220 : https://jumpit.saramin.co.kr/position/49219
상세 페이지 49378 : https://jumpit.saramin.co.kr/position/49377
상세 페이지 50001 : https://jumpit.saramin.co.kr/position/50000
상세 페이지 50489 : https://jumpit.saramin.co.kr/position/50488
상세 페이지 49153 : https://jumpit.saramin.co.kr/position/49152
상세 페이지 49030 : https://jumpit.saramin.co.kr/position/49029
상세 페이지 50297 : https://jumpit.saramin.co.kr/position/50296
상세 페이지 49311 : https://jumpit.saramin.co.kr/position/49310
상세 페이지 49379 : https://jumpit.saramin.co.kr/position/49378
상세 페이지 50038 : https://jumpit.saramin.co.kr/position/50037
상세 페이지 50303 : https://jumpit.saramin.co.kr/position/50302
상세 페이지 50490 : https://jumpit.saramin.co.kr/position/50489
상세 페이지 50495 : https://jumpit.saramin.co.kr/position/50494
상세 페이지 49894 : https://jumpit.saramin.co.kr/position/49893
상세 페이지 48721 : https://jumpit.saramin.co.kr/position/48720
상세 페이지 49375 : https://jumpit.saramin.co.kr/position/49374
상세 페이지 49789 : https://jumpit.saramin.co.kr/position/49788
상세 페이지 49209 : https://jumpit.saramin.co.kr/position/49208
상세 페이지 49891 : https://jumpit.saramin.co.kr/position/49890
상세 페이지 49767 : https://jumpit.saramin.co.kr/position/49766
상세 페이지 49179 : https://jumpit.saramin.co.kr/position/49178
상세 페이지 49584 : https://jumpit.saramin.co.kr/position/49583
상세 페이지 49859 : https://jumpit.saramin.co.kr/position/49858
상세 페이지 49317 : https://jumpit.saramin.co.kr/position/49316
상세 페이지 49157 : https://jumpit.saramin.co.kr/position/49156
상세 페이지 49892 : https://jumpit.saramin.co.kr/position/49891
상세 페이지 49159 : https://jumpit.saramin.co.kr/position/49158
상세 페이지 49310 : https://jumpit.saramin.co.kr/position/49309
상세 페이지 49712 : https://jumpit.saramin.co.kr/position/49711
상세 페이지 48879 : https://jumpit.saramin.co.kr/position/48878
상세 페이지 49587 : https://jumpit.saramin.co.kr/position/49586
상세 페이지 49592 : https://jumpit.saramin.co.kr/position/49591
상세 페이지 49589 : https://jumpit.saramin.co.kr/position/49588
상세 페이지 49573 : https://jumpit.saramin.co.kr/position/49572
상세 페이지 49803 : https://jumpit.saramin.co.kr/position/49802
상세 페이지 49869 : https://jumpit.saramin.co.kr/position/49868
상세 페이지 49570 : https://jumpit.saramin.co.kr/position/49569
상세 페이지 49572 : https://jumpit.saramin.co.kr/position/49571
상세 페이지 49251 : https://jumpit.saramin.co.kr/position/49250
상세 페이지 49696 : https://jumpit.saramin.co.kr/position/49695
상세 페이지 12031 : https://jumpit.saramin.co.kr/position/12030
상세 페이지 49649 : https://jumpit.saramin.co.kr/position/49648
상세 페이지 49419 : https://jumpit.saramin.co.kr/position/49418
상세 페이지 49689 : https://jumpit.saramin.co.kr/position/49688
상세 페이지 49500 : https://jumpit.saramin.co.kr/position/49499
상세 페이지 48732 : https://jumpit.saramin.co.kr/position/48731
상세 페이지 50030 : https://jumpit.saramin.co.kr/position/50029
상세 페이지 49555 : https://jumpit.saramin.co.kr/position/49554
상세 페이지 49458 : https://jumpit.saramin.co.kr/position/49457
상세 페이지 50193 : https://jumpit.saramin.co.kr/position/50192
상세 페이지 50028 : https://jumpit.saramin.co.kr/position/50027
상세 페이지 49741 : https://jumpit.saramin.co.kr/position/49740
상세 페이지 48739 : https://jumpit.saramin.co.kr/position/48738
상세 페이지 49682 : https://jumpit.saramin.co.kr/position/49681
상세 페이지 49181 : https://jumpit.saramin.co.kr/position/49180
상세 페이지 49005 : https://jumpit.saramin.co.kr/position/49004
상세 페이지 49482 : https://jumpit.saramin.co.kr/position/49481
상세 페이지 50080 : https://jumpit.saramin.co.kr/position/50079
상세 페이지 49542 : https://jumpit.saramin.co.kr/position/49541
상세 페이지 49324 : https://jumpit.saramin.co.kr/position/49323
상세 페이지 50501 : https://jumpit.saramin.co.kr/position/50500
상세 페이지 50500 : https://jumpit.saramin.co.kr/position/50499
상세 페이지 48950 : https://jumpit.saramin.co.kr/position/48949
상세 페이지 49299 : https://jumpit.saramin.co.kr/position/49298
상세 페이지 49524 : https://jumpit.saramin.co.kr/position/49523
상세 페이지 50075 : https://jumpit.saramin.co.kr/position/50074
상세 페이지 49297 : https://jumpit.saramin.co.kr/position/49296
상세 페이지 49449 : https://jumpit.saramin.co.kr/position/49448
상세 페이지 50504 : https://jumpit.saramin.co.kr/position/50503
상세 페이지 49980 : https://jumpit.saramin.co.kr/position/49979
상세 페이지 49821 : https://jumpit.saramin.co.kr/position/49820
상세 페이지 49588 : https://jumpit.saramin.co.kr/position/49587
상세 페이지 49148 : https://jumpit.saramin.co.kr/position/49147
상세 페이지 49590 : https://jumpit.saramin.co.kr/position/49589
상세 페이지 49531 : https://jumpit.saramin.co.kr/position/49530
상세 페이지 49973 : https://jumpit.saramin.co.kr/position/49972
상세 페이지 50390 : https://jumpit.saramin.co.kr/position/50389
상세 페이지 50037 : https://jumpit.saramin.co.kr/position/50036
상세 페이지 49586 : https://jumpit.saramin.co.kr/position/49585
상세 페이지 50039 : https://jumpit.saramin.co.kr/position/50038
상세 페이지 49768 : https://jumpit.saramin.co.kr/position/49767
상세 페이지 49745 : https://jumpit.saramin.co.kr/position/49744
상세 페이지 50006 : https://jumpit.saramin.co.kr/position/50005
상세 페이지 48709 : https://jumpit.saramin.co.kr/position/48708
상세 페이지 48708 : https://jumpit.saramin.co.kr/position/48707
상세 페이지 49650 : https://jumpit.saramin.co.kr/position/49649
상세 페이지 49131 : https://jumpit.saramin.co.kr/position/49130
상세 페이지 48733 : https://jumpit.saramin.co.kr/position/48732
상세 페이지 49866 : https://jumpit.saramin.co.kr/position/49865
상세 페이지 50304 : https://jumpit.saramin.co.kr/position/50303
상세 페이지 50277 : https://jumpit.saramin.co.kr/position/50276
상세 페이지 50491 : https://jumpit.saramin.co.kr/position/50490
상세 페이지 50419 : https://jumpit.saramin.co.kr/position/50418
상세 페이지 50272 : https://jumpit.saramin.co.kr/position/50271
상세 페이지 50122 : https://jumpit.saramin.co.kr/position/50121
상세 페이지 49177 : https://jumpit.saramin.co.kr/position/49176
상세 페이지 50191 : https://jumpit.saramin.co.kr/position/50190
상세 페이지 48740 : https://jumpit.saramin.co.kr/position/48739
상세 페이지 50155 : https://jumpit.saramin.co.kr/position/50154
상세 페이지 50487 : https://jumpit.saramin.co.kr/position/50486
상세 페이지 50245 : https://jumpit.saramin.co.kr/position/50244
상세 페이지 49975 : https://jumpit.saramin.co.kr/position/49974
상세 페이지 49893 : https://jumpit.saramin.co.kr/position/49892
상세 페이지 49180 : https://jumpit.saramin.co.kr/position/49179
상세 페이지 49053 : https://jumpit.saramin.co.kr/position/49052
상세 페이지 49417 : https://jumpit.saramin.co.kr/position/49416
상세 페이지 49603 : https://jumpit.saramin.co.kr/position/49602
상세 페이지 31071 : https://jumpit.saramin.co.kr/position/31070
상세 페이지 49716 : https://jumpit.saramin.co.kr/position/49715
상세 페이지 50018 : https://jumpit.saramin.co.kr/position/50017
상세 페이지 48878 : https://jumpit.saramin.co.kr/position/48877
상세 페이지 49715 : https://jumpit.saramin.co.kr/position/49714
상세 페이지 49943 : https://jumpit.saramin.co.kr/position/49942
상세 페이지 49178 : https://jumpit.saramin.co.kr/position/49177
상세 페이지 50576 : https://jumpit.saramin.co.kr/position/50575
상세 페이지 50573 : https://jumpit.saramin.co.kr/position/50572
상세 페이지 49544 : https://jumpit.saramin.co.kr/position/49543
상세 페이지 49051 : https://jumpit.saramin.co.kr/position/49050
상세 페이지 50167 : https://jumpit.saramin.co.kr/position/50166
상세 페이지 49746 : https://jumpit.saramin.co.kr/position/49745
상세 페이지 48979 : https://jumpit.saramin.co.kr/position/48978
상세 페이지 49742 : https://jumpit.saramin.co.kr/position/49741
상세 페이지 49848 : https://jumpit.saramin.co.kr/position/49847
상세 페이지 49261 : https://jumpit.saramin.co.kr/position/49260
상세 페이지 49459 : https://jumpit.saramin.co.kr/position/49458
상세 페이지 49268 : https://jumpit.saramin.co.kr/position/49267
상세 페이지 49546 : https://jumpit.saramin.co.kr/position/49545
상세 페이지 49690 : https://jumpit.saramin.co.kr/position/49689
상세 페이지 49456 : https://jumpit.saramin.co.kr/position/49455
상세 페이지 49562 : https://jumpit.saramin.co.kr/position/49561
상세 페이지 49842 : https://jumpit.saramin.co.kr/position/49841
상세 페이지 49762 : https://jumpit.saramin.co.kr/position/49761
상세 페이지 50081 : https://jumpit.saramin.co.kr/position/50080
상세 페이지 50518 : https://jumpit.saramin.co.kr/position/50517
상세 페이지 49728 : https://jumpit.saramin.co.kr/position/49727
상세 페이지 49847 : https://jumpit.saramin.co.kr/position/49846
상세 페이지 49348 : https://jumpit.saramin.co.kr/position/49347
상세 페이지 49420 : https://jumpit.saramin.co.kr/position/49419
상세 페이지 50029 : https://jumpit.saramin.co.kr/position/50028
상세 페이지 46045 : https://jumpit.saramin.co.kr/position/46044
상세 페이지 49867 : https://jumpit.saramin.co.kr/position/49866
상세 페이지 49897 : https://jumpit.saramin.co.kr/position/49896
상세 페이지 50015 : https://jumpit.saramin.co.kr/position/50014
상세 페이지 49974 : https://jumpit.saramin.co.kr/position/49973
상세 페이지 50189 : https://jumpit.saramin.co.kr/position/50188
상세 페이지 49325 : https://jumpit.saramin.co.kr/position/49324
상세 페이지 49754 : https://jumpit.saramin.co.kr/position/49753
상세 페이지 49127 : https://jumpit.saramin.co.kr/position/49126
상세 페이지 49298 : https://jumpit.saramin.co.kr/position/49297
상세 페이지 50685 : https://jumpit.saramin.co.kr/position/50684
상세 페이지 50357 : https://jumpit.saramin.co.kr/position/50356
상세 페이지 49129 : https://jumpit.saramin.co.kr/position/49128
상세 페이지 50356 : https://jumpit.saramin.co.kr/position/50355
상세 페이지 50162 : https://jumpit.saramin.co.kr/position/50161
상세 페이지 50221 : https://jumpit.saramin.co.kr/position/50220
상세 페이지 50392 : https://jumpit.saramin.co.kr/position/50391
상세 페이지 50503 : https://jumpit.saramin.co.kr/position/50502
상세 페이지 49042 : https://jumpit.saramin.co.kr/position/49041
상세 페이지 49673 : https://jumpit.saramin.co.kr/position/49672
상세 페이지 49097 : https://jumpit.saramin.co.kr/position/49096
상세 페이지 48722 : https://jumpit.saramin.co.kr/position/48721
상세 페이지 49519 : https://jumpit.saramin.co.kr/position/49518
상세 페이지 49518 : https://jumpit.saramin.co.kr/position/49517
상세 페이지 49763 : https://jumpit.saramin.co.kr/position/49762
상세 페이지 50354 : https://jumpit.saramin.co.kr/position/50353
상세 페이지 50569 : https://jumpit.saramin.co.kr/position/50568
상세 페이지 49517 : https://jumpit.saramin.co.kr/position/49516
상세 페이지 50342 : https://jumpit.saramin.co.kr/position/50341
상세 페이지 50278 : https://jumpit.saramin.co.kr/position/50277
상세 페이지 50571 : https://jumpit.saramin.co.kr/position/50570
상세 페이지 50157 : https://jumpit.saramin.co.kr/position/50156
상세 페이지 49195 : https://jumpit.saramin.co.kr/position/49194
상세 페이지 49697 : https://jumpit.saramin.co.kr/position/49696
상세 페이지 49196 : https://jumpit.saramin.co.kr/position/49195
상세 페이지 48951 : https://jumpit.saramin.co.kr/position/48950
상세 페이지 49171 : https://jumpit.saramin.co.kr/position/49170
상세 페이지 49172 : https://jumpit.saramin.co.kr/position/49171
상세 페이지 49448 : https://jumpit.saramin.co.kr/position/49447
상세 페이지 49491 : https://jumpit.saramin.co.kr/position/49490
상세 페이지 49194 : https://jumpit.saramin.co.kr/position/49193
상세 페이지 48945 : https://jumpit.saramin.co.kr/position/48944
상세 페이지 48946 : https://jumpit.saramin.co.kr/position/48945
상세 페이지 48693 : https://jumpit.saramin.co.kr/position/48692
상세 페이지 49213 : https://jumpit.saramin.co.kr/position/49212
상세 페이지 49743 : https://jumpit.saramin.co.kr/position/49742
상세 페이지 49409 : https://jumpit.saramin.co.kr/position/49408
상세 페이지 49212 : https://jumpit.saramin.co.kr/position/49211
상세 페이지 50166 : https://jumpit.saramin.co.kr/position/50165
상세 페이지 50361 : https://jumpit.saramin.co.kr/position/50360
상세 페이지 48887 : https://jumpit.saramin.co.kr/position/48886
상세 페이지 50185 : https://jumpit.saramin.co.kr/position/50184
상세 페이지 49228 : https://jumpit.saramin.co.kr/position/49227
상세 페이지 50082 : https://jumpit.saramin.co.kr/position/50081
상세 페이지 50313 : https://jumpit.saramin.co.kr/position/50312
상세 페이지 49372 : https://jumpit.saramin.co.kr/position/49371
상세 페이지 49304 : https://jumpit.saramin.co.kr/position/49303
상세 페이지 49369 : https://jumpit.saramin.co.kr/position/49368
상세 페이지 49671 : https://jumpit.saramin.co.kr/position/49670
상세 페이지 49782 : https://jumpit.saramin.co.kr/position/49781
상세 페이지 49825 : https://jumpit.saramin.co.kr/position/49824
상세 페이지 49591 : https://jumpit.saramin.co.kr/position/49590
상세 페이지 49382 : https://jumpit.saramin.co.kr/position/49381
상세 페이지 49526 : https://jumpit.saramin.co.kr/position/49525
상세 페이지 49659 : https://jumpit.saramin.co.kr/position/49658
상세 페이지 49641 : https://jumpit.saramin.co.kr/position/49640
상세 페이지 49300 : https://jumpit.saramin.co.kr/position/49299
상세 페이지 49128 : https://jumpit.saramin.co.kr/position/49127
상세 페이지 49184 : https://jumpit.saramin.co.kr/position/49183
상세 페이지 50031 : https://jumpit.saramin.co.kr/position/50030
상세 페이지 49331 : https://jumpit.saramin.co.kr/position/49330
상세 페이지 50190 : https://jumpit.saramin.co.kr/position/50189
상세 페이지 49942 : https://jumpit.saramin.co.kr/position/49941
상세 페이지 50008 : https://jumpit.saramin.co.kr/position/50007
상세 페이지 49125 : https://jumpit.saramin.co.kr/position/49124
상세 페이지 50430 : https://jumpit.saramin.co.kr/position/50429
상세 페이지 49896 : https://jumpit.saramin.co.kr/position/49895
상세 페이지 49994 : https://jumpit.saramin.co.kr/position/49993
상세 페이지 49529 : https://jumpit.saramin.co.kr/position/49528
상세 페이지 50130 : https://jumpit.saramin.co.kr/position/50129
상세 페이지 50358 : https://jumpit.saramin.co.kr/position/50357
상세 페이지 50159 : https://jumpit.saramin.co.kr/position/50158
상세 페이지 48738 : https://jumpit.saramin.co.kr/position/48737
상세 페이지 49312 : https://jumpit.saramin.co.kr/position/49311
상세 페이지 50181 : https://jumpit.saramin.co.kr/position/50180
상세 페이지 49543 : https://jumpit.saramin.co.kr/position/49542
상세 페이지 49052 : https://jumpit.saramin.co.kr/position/49051
상세 페이지 49476 : https://jumpit.saramin.co.kr/position/49475
상세 페이지 49599 : https://jumpit.saramin.co.kr/position/49598
상세 페이지 49598 : https://jumpit.saramin.co.kr/position/49597
상세 페이지 49427 : https://jumpit.saramin.co.kr/position/49426
상세 페이지 48949 : https://jumpit.saramin.co.kr/position/48948
상세 페이지 49323 : https://jumpit.saramin.co.kr/position/49322
상세 페이지 50019 : https://jumpit.saramin.co.kr/position/50018
상세 페이지 49816 : https://jumpit.saramin.co.kr/position/49815
상세 페이지 50291 : https://jumpit.saramin.co.kr/position/50290
상세 페이지 49907 : https://jumpit.saramin.co.kr/position/49906
상세 페이지 48694 : https://jumpit.saramin.co.kr/position/48693
상세 페이지 49457 : https://jumpit.saramin.co.kr/position/49456
상세 페이지 47305 : https://jumpit.saramin.co.kr/position/47304
상세 페이지 50359 : https://jumpit.saramin.co.kr/position/50358
상세 페이지 50574 : https://jumpit.saramin.co.kr/position/50573
상세 페이지 50199 : https://jumpit.saramin.co.kr/position/50198
상세 페이지 48943 : https://jumpit.saramin.co.kr/position/48942
상세 페이지 49527 : https://jumpit.saramin.co.kr/position/49526
상세 페이지 49525 : https://jumpit.saramin.co.kr/position/49524
상세 페이지 49072 : https://jumpit.saramin.co.kr/position/49071
상세 페이지 49415 : https://jumpit.saramin.co.kr/position/49414
상세 페이지 50168 : https://jumpit.saramin.co.kr/position/50167
상세 페이지 49264 : https://jumpit.saramin.co.kr/position/49263
상세 페이지 48948 : https://jumpit.saramin.co.kr/position/48947
상세 페이지 50417 : https://jumpit.saramin.co.kr/position/50416
상세 페이지 50563 : https://jumpit.saramin.co.kr/position/50562
상세 페이지 49377 : https://jumpit.saramin.co.kr/position/49376
상세 페이지 48934 : https://jumpit.saramin.co.kr/position/48933
상세 페이지 49795 : https://jumpit.saramin.co.kr/position/49794
상세 페이지 49616 : https://jumpit.saramin.co.kr/position/49615
상세 페이지 49454 : https://jumpit.saramin.co.kr/position/49453
상세 페이지 49596 : https://jumpit.saramin.co.kr/position/49595
상세 페이지 49597 : https://jumpit.saramin.co.kr/position/49596
상세 페이지 49567 : https://jumpit.saramin.co.kr/position/49566
상세 페이지 49260 : https://jumpit.saramin.co.kr/position/49259
상세 페이지 49944 : https://jumpit.saramin.co.kr/position/49943
상세 페이지 50182 : https://jumpit.saramin.co.kr/position/50181
상세 페이지 50121 : https://jumpit.saramin.co.kr/position/50120
상세 페이지 49029 : https://jumpit.saramin.co.kr/position/49028
상세 페이지 49447 : https://jumpit.saramin.co.kr/position/49446
상세 페이지 49418 : https://jumpit.saramin.co.kr/position/49417
상세 페이지 49414 : https://jumpit.saramin.co.kr/position/49413
상세 페이지 49026 : https://jumpit.saramin.co.kr/position/49025
상세 페이지 49357 : https://jumpit.saramin.co.kr/position/49356
상세 페이지 49138 : https://jumpit.saramin.co.kr/position/49137
상세 페이지 49014 : https://jumpit.saramin.co.kr/position/49013
상세 페이지 49321 : https://jumpit.saramin.co.kr/position/49320
상세 페이지 49477 : https://jumpit.saramin.co.kr/position/49476
상세 페이지 49428 : https://jumpit.saramin.co.kr/position/49427
상세 페이지 49499 : https://jumpit.saramin.co.kr/position/49498
상세 페이지 49100 : https://jumpit.saramin.co.kr/position/49099
상세 페이지 49733 : https://jumpit.saramin.co.kr/position/49732
상세 페이지 49259 : https://jumpit.saramin.co.kr/position/49258
상세 페이지 48898 : https://jumpit.saramin.co.kr/position/48897
상세 페이지 16539 : https://jumpit.saramin.co.kr/position/16538
상세 페이지 49370 : https://jumpit.saramin.co.kr/position/49369
상세 페이지 49167 : https://jumpit.saramin.co.kr/position/49166
상세 페이지 49530 : https://jumpit.saramin.co.kr/position/49529
상세 페이지 49240 : https://jumpit.saramin.co.kr/position/49239
상세 페이지 49239 : https://jumpit.saramin.co.kr/position/49238
상세 페이지 49426 : https://jumpit.saramin.co.kr/position/49425

In [3]:
detailDataFrame = pd.DataFrame(data)
detailDataFrame.set_index('id', inplace=True)

In [4]:
detailDataFrame

,title,company,pride,techStack,mainWork,requirements,preferential,welfare,procedures,career,education,closedAt,jobLocation
id,,,,,,,,,,,,,
49678,서버개발팀 모바일 개발자(경력),사이버다임,"[🚆2호선 역세권 기업, #유연근무제, #도서구입비지원]","[Android Studio, Node.js, Webpack, Redux, Reac...","[• 자사 솔루션 모바일 개발, - Destiny ECM(데스티니 ECM)은 고객사...","[• 관련 경력을 5년 이상 보유한 분, • React Native 개발이 가능한 ...","[• 채팅 클라이언트 개발 경험이 있으신 분, • 기업용 솔루션 개발 경험이 있으신...","[직원 중심의 조직문화를 만들어갑니다., 유연근무제와 자유로운 연차 사용으로 일과 ...",[• 서류전형 → 1차 면접 → 2차 면접 (필요 시) → 입사 협의],경력 5~15년,"대학졸업(2,3년) 이상",2025년 05월 24일,"서울 송파구 올림픽로 299, 12층지도보기·주소복사"
48941,BE Engineer,이마고웍스,"[🚆3호선 역세권 기업, 💰시리즈B 투자유치, #반바지/슬리퍼 OK, #수평적조직,...","[MongoDB, TypeScript, Rust, NoSql, AWS, NestJS...","[• 각 포지션의 기술을 바탕으로 Dentbird Solutions 제품화, • 솔...","[• 주도적으로 문제를 해결하는 능력이 뛰어나신 분, • 자유롭게 토론하고 의견을 ...","[• 개발환경, 프로그래밍 언어에 제한 없이 다양한 환경 및 언어를 편하게 하실 수...","[직원이 편해야 회사가 잘된다!, • 수평적인 조직 문화, • 자율 출퇴근제 운영,...","[*서류 심사 - 1차 면접 - 2차 면접 - 입사 제안 , *필요한 경우 지원...",경력 5~8년,대학교졸업(4년) 이상,2025년 05월 11일,"서울 강남구 강남대로 636 1층, 2층 (신사동, 두원빌딩)지도보기·주소복사"
49281,신입 개발자 채용,하이퍼에픽,"[🚆9호선 역세권 기업, 🏢코퍼스코리아 계열사]","[Git, Kotlin, TypeScript, Spring Boot, Node.js...","[• 어플리케이션 백엔드 서버 개발 및 유지보수, • 관련 부서와 긴밀하게 협업하면...","[• spring boot, kotlin 경험이 있는 분, • postgresq...","[• type script 경험이 있는 분, • nodejs 경험이 있는 분]","[• 퇴직금, • 4대보험, • 간식 제공, • 자율 복장, • 수평적 조...","[[근무환경], • 고용형태 : 정규직, • 근무지역 : 서울 강남구, • 급여조건...",신입~2년,무관,2025년 05월 16일,"서울 강남구 강남대로 484, 602호 (논현동,99빌딩)지도보기·주소복사"
49577,머신러닝 엔지니어 - 시니어,심플랫폼,[],"[AI/인공지능, Helm, Linux, Kubernetes, TensorFlow,...","[[[ 산업용 ML 모델 개발 및 최적화 ]], • 산업용 시계열 및 비전 데이터(...","[• 데이터 과학 혹은 소프트웨어 공학 전공인 분, • 머신 러닝 및 소프트웨어 공...",[• Kubernetes 기반 ML 서비스 운영 경험이 있으면 좋아요. (Docke...,"[• 4대 사회보험 가입, • 주5일 근무, • 법정퇴직금, • 경조휴가 및 경조금...",[• 서류 전형 - 코딩테스트(SW엔지니어링+데이터분석) - 기술 면접 - 임원 면...,경력 6~15년,대학교졸업(4년) 이상,2025년 05월 22일,"서울 금천구 가산디지털1로 226, 2003호, 2004호 (가산동,에이스하이엔드타..."
48390,임베디드 S/W 개발자,넥스트랩,"[🚆2호선 역세권 기업, #유연근무제]","[Linux, C++, Embedded, Python, Network]","[• 자사 임베디드 제품의 소프트웨어 개선 및 신규 장비의 소프트웨어 개발, ...","[• 소프트웨어 개발관련 전공 4년제 학사 이상 (컴퓨터공학, 정보통신, 전기전자 ...","[• 네트워크 , 영상 관련 데이터 처리, 분석, • 데이터 분석, 알고리즘 관련 ...","[• 유연근무제 (2주 80시간, 코어타임: 12~16시), • 연차, 반차, 반반...",[서류검토 > 1차 면접 (실무진) > 코딩테스트 > 2차 면접(대표이사) > 연봉...,신입~5년,대학교졸업(4년) 이상,2025년 05월 24일,"서울 강남구 선릉로90길 40, 4층지도보기·주소복사"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
50649,백엔드 서버 개발자 [경력 7년 이상],아이피샵,"[🚆5호선 역세권 기업, #자유복장, #전공우대]","[MySQL, Java, JSP, SQL, MariaDB]",[• 자사 서비스 개발 및 유지보수],"[• 경력 7년 이상, • Java 및 기타 프로그래밍 언어에 대한 이해가 높으신 ...","[• SI 프로젝트 경험자, • 윈도우 및 리눅스 서버 관리 경험자, • 관련 학과...","[• 사내카페운영 : 라운지 스낵바, 음료, 커피 무제한 제공, • 자율복장 : 본...","[• 채용절차 : 서류전형 -> 면접전형 -> 최종합격, • 접수방법 : 온라인 입...",경력 7~10년,무관,2025년 06월 09일,서울시 강남구 언주로 536 태승빌딩 5F~7F지도보기·주소복사
49627,SAP CO 모듈 담당자 채용,영원아웃도어,[🏢영원 계열사],"[Microsoft Excel, SAP]","[• SAP CO(Controlling) 모듈 운영 및 유지보수, • SAP CO,...","[• 학력: 대학교졸업(4년) 이상, • 경력: 5년이상]","[• ABAP Skill 보유자, • 패션/유통업체 SAP운영 경험자, • 영어회화...","[• 연금/보험, - 국민연금, 고용보험, 산재보험, 건강보험, , • 건강...","[• 근무조건, - 근무형태: 정규직, - 급 여: 면접 후 결정...",경력 5~10년,대학교졸업(4년) 이상,2025년 05월 22일,경기 성남시 중원구 사기막골로 169지도보기·주소복사
49729,통신장비 연구개발 채용 - 주임/대리급,혜성테크윈,[],"[Ccna, Embedded, Network, Ccnp]","[• 통신장비 연구개발(H/W 분석 및 설계 등) , • 조달우수 수행 업무 ]","[• 초대졸 이상, • 경력 2년 이상]","[• 통신장비(L2/L3스위치 장비 등) 관련 개발 유경험자., • R&D 연구개발...","[- 건강보험, 국민연금, 고용보험 가입 등의 사회보험을 제공, - 중식 제공, 성...",[# 혜성테크윈은 구직자가 서류 반환을 요구하지 않을 경우 개인정보 보호조치에 따라...,경력 2~5년,"대학졸업(2,3년) 이상",2025년 05월 26일,"경기 성남시 중원구 사기막골로 99 성남센트럴비즈타워2차 B동 1508호, 1509..."
50250,네트워크 엔지니어 경력(10년이상),텐빌리언,[],[Network],"[• 네트워크 운영 관리, • 장애 발생시 장비 교체 지원, • 보안장비 기술 지원...","[• 네트워크 엔지니어 이해도 있는 자, • 경력자]",[• Cisco 자격증 소지자],"[-자유로운 환경의 업무 스타일, -자유로운 연차 사용 및 시차 출퇴근, -생일 연...",[ 서류전형 > 면접전형 > 최종합격],경력 10~15년,대학교졸업(4년) 이상,2025년 06월 02일,서울 구로구 구로동 1127-26지도보기·주소복사
50049,임베디드 개발자 신입 채용,에프엘이에스,"[🚆2호선 역세권 기업, #전공우대]","[HW, C++, FW, Python, C, RTOS]","[ㆍ임베디드 시스템 디버깅 및 성능 최적화, ㆍ실시간 운영체제(RTOS) 기반 개발...","[ㆍ대졸 이상, ㆍIoT 및 스마트 그리드 통신 표준 관련 프로젝트 경험 보유, ㆍ...","[ㆍ해당직무 근무경험, ㆍ관련학과 전공자 우대, ㆍ스마트 그리드 관련 경험우대(OC...","[• 자율 출퇴근, • 스톡옵션 지급 가능, • 맥북 지급, • 도서, 교육, 세미...",[],신입,대학교졸업(4년) 이상,2025년 06월 08일,서울시 강서구 마곡동 757 두산더랜드파크 A동 614호지도보기·주소복사

In [5]:
toJsonFile(detailDataFrame, 20250511, 'Detail')

In [6]:
detailDataFrame = pd.read_json('../Data_Files/Crawling_DataFile_DetailPage_json_20250511.txt')

In [7]:

detailDataFrame.head(5)

,title,company,pride,techStack,mainWork,requirements,preferential,welfare,procedures,career,education,closedAt,jobLocation,date
49678,서버개발팀 모바일 개발자(경력),사이버다임,"[🚆2호선 역세권 기업, #유연근무제, #도서구입비지원]","[Android Studio, Node.js, Webpack, Redux, Reac...","[• 자사 솔루션 모바일 개발, - Destiny ECM(데스티니 ECM)은 고객사...","[• 관련 경력을 5년 이상 보유한 분, • React Native 개발이 가능한 ...","[• 채팅 클라이언트 개발 경험이 있으신 분, • 기업용 솔루션 개발 경험이 있으신...","[직원 중심의 조직문화를 만들어갑니다., 유연근무제와 자유로운 연차 사용으로 일과 ...",[• 서류전형 → 1차 면접 → 2차 면접 (필요 시) → 입사 협의],경력 5~15년,"대학졸업(2,3년) 이상",2025년 05월 24일,"서울 송파구 올림픽로 299, 12층지도보기·주소복사",2025년05월11일
48941,BE Engineer,이마고웍스,"[🚆3호선 역세권 기업, 💰시리즈B 투자유치, #반바지/슬리퍼 OK, #수평적조직,...","[MongoDB, TypeScript, Rust, NoSql, AWS, NestJS...","[• 각 포지션의 기술을 바탕으로 Dentbird Solutions 제품화, • 솔...","[• 주도적으로 문제를 해결하는 능력이 뛰어나신 분, • 자유롭게 토론하고 의견을 ...","[• 개발환경, 프로그래밍 언어에 제한 없이 다양한 환경 및 언어를 편하게 하실 수...","[직원이 편해야 회사가 잘된다!, • 수평적인 조직 문화, • 자율 출퇴근제 운영,...","[*서류 심사 - 1차 면접 - 2차 면접 - 입사 제안 , *필요한 경우 지원...",경력 5~8년,대학교졸업(4년) 이상,2025년 05월 11일,"서울 강남구 강남대로 636 1층, 2층 (신사동, 두원빌딩)지도보기·주소복사",2025년05월11일
49281,신입 개발자 채용,하이퍼에픽,"[🚆9호선 역세권 기업, 🏢코퍼스코리아 계열사]","[Git, Kotlin, TypeScript, Spring Boot, Node.js...","[• 어플리케이션 백엔드 서버 개발 및 유지보수, • 관련 부서와 긴밀하게 협업하면...","[• spring boot, kotlin 경험이 있는 분, • postgresq...","[• type script 경험이 있는 분, • nodejs 경험이 있는 분]","[• 퇴직금, • 4대보험, • 간식 제공, • 자율 복장, • 수평적 조...","[[근무환경], • 고용형태 : 정규직, • 근무지역 : 서울 강남구, • 급여조건...",신입~2년,무관,2025년 05월 16일,"서울 강남구 강남대로 484, 602호 (논현동,99빌딩)지도보기·주소복사",2025년05월11일
49577,머신러닝 엔지니어 - 시니어,심플랫폼,[],"[AI/인공지능, Helm, Linux, Kubernetes, TensorFlow,...","[[[ 산업용 ML 모델 개발 및 최적화 ]], • 산업용 시계열 및 비전 데이터(...","[• 데이터 과학 혹은 소프트웨어 공학 전공인 분, • 머신 러닝 및 소프트웨어 공...",[• Kubernetes 기반 ML 서비스 운영 경험이 있으면 좋아요. (Docke...,"[• 4대 사회보험 가입, • 주5일 근무, • 법정퇴직금, • 경조휴가 및 경조금...",[• 서류 전형 - 코딩테스트(SW엔지니어링+데이터분석) - 기술 면접 - 임원 면...,경력 6~15년,대학교졸업(4년) 이상,2025년 05월 22일,"서울 금천구 가산디지털1로 226, 2003호, 2004호 (가산동,에이스하이엔드타...",2025년05월11일
48390,임베디드 S/W 개발자,넥스트랩,"[🚆2호선 역세권 기업, #유연근무제]","[Linux, C++, Embedded, Python, Network]","[• 자사 임베디드 제품의 소프트웨어 개선 및 신규 장비의 소프트웨어 개발, ...","[• 소프트웨어 개발관련 전공 4년제 학사 이상 (컴퓨터공학, 정보통신, 전기전자 ...","[• 네트워크 , 영상 관련 데이터 처리, 분석, • 데이터 분석, 알고리즘 관련 ...","[• 유연근무제 (2주 80시간, 코어타임: 12~16시), • 연차, 반차, 반반...",[서류검토 > 1차 면접 (실무진) > 코딩테스트 > 2차 면접(대표이사) > 연봉...,신입~5년,대학교졸업(4년) 이상,2025년 05월 24일,"서울 강남구 선릉로90길 40, 4층지도보기·주소복사",2025년05월11일