In [4]:
from Jumpit_Crawling_Functions import *

In [2]:
data = crawlingDetailPage()

Loading: 0page [00:00, ?page/s]

Loading: 1page [00:00,  4.59page/s]
Loading: 1page [00:00,  6.41page/s]
Loading: 1page [00:00,  6.27page/s]
Loading: 1page [00:00,  7.41page/s]
Loading: 1page [00:00,  7.21page/s]
Loading: 1page [00:00,  7.05page/s]
Loading: 1page [00:00,  6.99page/s]
Loading: 1page [00:00,  6.41page/s]
Loading: 1page [00:00,  6.09page/s]
Loading: 1page [00:00,  6.80page/s]
Loading: 1page [00:00,  7.08page/s]
Loading: 1page [00:00,  5.47page/s]
Loading: 1page [00:00,  5.95page/s]
Loading: 1page [00:00,  6.85page/s]
Loading: 1page [00:00,  6.27page/s]
Loading: 1page [00:00,  6.51page/s]
Loading: 1page [00:00,  6.09page/s]
Loading: 1page [00:00,  6.38page/s]
Loading: 1page [00:00,  5.75page/s]
Loading: 1page [00:00,  6.16page/s]
Loading: 1page [00:00,  6.20page/s]
Loading: 1page [00:00,  6.06page/s]
Loading: 1page [00:00,  5.88page/s]
Loading: 1page [00:00,  5.53page/s]
Loading: 1page [00:00,  6.12page/s]
Loading: 1page [00:00,  6.14page/s]
Loading: 1page [00:00,  5.79page/s]
Loading: 1page [00:00,  6.11page/s]
Loading: 1page [00:00,  5.96page/s]
Loading: 1page [00:00,  5.71page/s]
Loading: 1page [00:00,  5.55page/s]
Loading: 1page [00:00,  5.68page/s]
Loading: 1page [00:00,  5.64page/s]
Loading: 1page [00:00,  5.33page/s]
Loading: 1page [00:00,  5.88page/s]
Loading: 1page [00:00,  6.41page/s]
Loading: 1page [00:00,  6.20page/s]
Loading: 1page [00:00,  5.73page/s]
Loading: 1page [00:00,  5.76page/s]
Loading: 1page [00:00,  6.11page/s]
Loading: 1page [00:00,  5.58page/s]
Loading: 1page [00:00,  6.33page/s]
Loading: 1page [00:00,  5.07page/s]
Loading: 1page [00:00,  5.40page/s]
Loading: 1page [00:00,  5.76page/s]
Loading: 1page [00:00,  6.02page/s]
Loading: 1page [00:00,  1.02page/s]
Loading: 1page [00:00,  5.45page/s]
Loading: 1page [00:00,  5.44page/s]
Loading: 1page [00:00,  6.28page/s]
Loading: 1page [00:00,  5.56page/s]
Loading: 1page [00:00,  6.06page/s]
Loading: 1page [00:00,  6.31page/s]
Loading: 1page [00:00,  6.34page/s]
Loading: 1page [00:00,  6.14page/s]
Loading: 1page [00:00,  4.82page/s]
Loading: 1page [00:00,  5.83page/s]
Loading: 1page [00:00,  6.36page/s]
Loading: 1page [00:00,  6.59page/s]
Loading: 1page [00:00,  5.91page/s]
Loading: 1page [00:00,  6.50page/s]
Loading: 1page [00:00,  5.69page/s]
Loading: 1page [00:00,  5.49page/s]
Loading: 1page [00:00,  5.95page/s]
Loading: 1page [00:00,  5.36page/s]
Loading: 1page [00:00,  5.68page/s]
Loading: 1page [00:00,  4.91page/s]
Loading: 1page [00:00,  5.59page/s]
Loading: 1page [00:00,  5.04page/s]
Loading: 1page [00:00,  5.62page/s]
Loading: 1page [00:00,  6.24page/s]
Loading: 1page [00:00,  5.81page/s]
Loading: 1page [00:00,  5.96page/s]
Loading: 1page [00:00,  6.50page/s]
Loading: 1page [00:00,  6.46page/s]
Loading: 1page [00:00,  6.89page/s]
Loading: 1page [00:00,  6.00page/s]
Loading: 1page [00:00,  5.79page/s]
Loading: 1page [00:00,  5.43page/s]
Loading: 1page [00:00,  5.89page/s]
Loading: 1page [00:00,  5.51page/s]
Loading: 1page [00:00,  6.07page/s]
Loading: 1page [00:00,  5.43page/s]
Loading: 1page [00:00,  6.05page/s]
Loading: 1page [00:00,  5.77page/s]
Loading: 1page [00:00,  5.24page/s]
Loading: 1page [00:00,  6.11page/s]
Loading: 1page [00:00,  5.41page/s]
Loading: 1page [00:00,  5.78page/s]
Loading: 1page [00:00,  6.02page/s]
Loading: 1page [00:00,  7.90page/s]

모든 페이지 정보를 가져 왔습니다
상세 페이지 49679 : https://jumpit.saramin.co.kr/position/49678
상세 페이지 49208 : https://jumpit.saramin.co.kr/position/49207
상세 페이지 48942 : https://jumpit.saramin.co.kr/position/48941
상세 페이지 49282 : https://jumpit.saramin.co.kr/position/49281
상세 페이지 47833 : https://jumpit.saramin.co.kr/position/47832
상세 페이지 49681 : https://jumpit.saramin.co.kr/position/49680
상세 페이지 48941 : https://jumpit.saramin.co.kr/position/48940
상세 페이지 49578 : https://jumpit.saramin.co.kr/position/49577
상세 페이지 49028 : https://jumpit.saramin.co.kr/position/49027
상세 페이지 49617 : https://jumpit.saramin.co.kr/position/49616
상세 페이지 49437 : https://jumpit.saramin.co.kr/position/49436
상세 페이지 49102 : https://jumpit.saramin.co.kr/position/49101
상세 페이지 49687 : https://jumpit.saramin.co.kr/position/49686
상세 페이지 49843 : https://jumpit.saramin.co.kr/position/49842
상세 페이지 49680 : https://jumpit.saramin.co.kr/position/49679
상세 페이지 48391 : https://jumpit.saramin.co.kr/position/48390
상세 페이지 48886 : https://jumpit.saramin.co.kr/position/48885
상세 페이지 49230 : https://jumpit.saramin.co.kr/position/49229
상세 페이지 49464 : https://jumpit.saramin.co.kr/position/49463
상세 페이지 49890 : https://jumpit.saramin.co.kr/position/49889
상세 페이지 50005 : https://jumpit.saramin.co.kr/position/50004
상세 페이지 49553 : https://jumpit.saramin.co.kr/position/49552
상세 페이지 49085 : https://jumpit.saramin.co.kr/position/49084
상세 페이지 49358 : https://jumpit.saramin.co.kr/position/49357
상세 페이지 49210 : https://jumpit.saramin.co.kr/position/49209
상세 페이지 49050 : https://jumpit.saramin.co.kr/position/49049
상세 페이지 49211 : https://jumpit.saramin.co.kr/position/49210
상세 페이지 49466 : https://jumpit.saramin.co.kr/position/49465
상세 페이지 49595 : https://jumpit.saramin.co.kr/position/49594
상세 페이지 49155 : https://jumpit.saramin.co.kr/position/49154
상세 페이지 49465 : https://jumpit.saramin.co.kr/position/49464
상세 페이지 49289 : https://jumpit.saramin.co.kr/position/49288
상세 페이지 49761 : https://jumpit.saramin.co.kr/position/49760
상세 페이지 49646 : https://jumpit.saramin.co.kr/position/49645
상세 페이지 49371 : https://jumpit.saramin.co.kr/position/49370
상세 페이지 48844 : https://jumpit.saramin.co.kr/position/48843
상세 페이지 49720 : https://jumpit.saramin.co.kr/position/49719
상세 페이지 49242 : https://jumpit.saramin.co.kr/position/49241
상세 페이지 50495 : https://jumpit.saramin.co.kr/position/50494
상세 페이지 49152 : https://jumpit.saramin.co.kr/position/49151
상세 페이지 49789 : https://jumpit.saramin.co.kr/position/49788
상세 페이지 50297 : https://jumpit.saramin.co.kr/position/50296
상세 페이지 50152 : https://jumpit.saramin.co.kr/position/50151
상세 페이지 50038 : https://jumpit.saramin.co.kr/position/50037
상세 페이지 50488 : https://jumpit.saramin.co.kr/position/50487
상세 페이지 50493 : https://jumpit.saramin.co.kr/position/50492
상세 페이지 49790 : https://jumpit.saramin.co.kr/position/49789
상세 페이지 50245 : https://jumpit.saramin.co.kr/position/50244
상세 페이지 50257 : https://jumpit.saramin.co.kr/position/50256
상세 페이지 50277 : https://jumpit.saramin.co.kr/position/50276
상세 페이지 50489 : https://jumpit.saramin.co.kr/position/50488
상세 페이지 50261 : https://jumpit.saramin.co.kr/position/50260
상세 페이지 49209 : https://jumpit.saramin.co.kr/position/49208
상세 페이지 49892 : https://jumpit.saramin.co.kr/position/49891
상세 페이지 49376 : https://jumpit.saramin.co.kr/position/49375
상세 페이지 49220 : https://jumpit.saramin.co.kr/position/49219
상세 페이지 50156 : https://jumpit.saramin.co.kr/position/50155
상세 페이지 49285 : https://jumpit.saramin.co.kr/position/49284
상세 페이지 49153 : https://jumpit.saramin.co.kr/position/49152
상세 페이지 50323 : https://jumpit.saramin.co.kr/position/50322
상세 페이지 50490 : https://jumpit.saramin.co.kr/position/50489
상세 페이지 50303 : https://jumpit.saramin.co.kr/position/50302
상세 페이지 48721 : https://jumpit.saramin.co.kr/position/48720
상세 페이지 49311 : https://jumpit.saramin.co.kr/position/49310
상세 페이지 50154 : https://jumpit.saramin.co.kr/position/50153
상세 페이지 50494 : https://jumpit.saramin.co.kr/position/50493
상세 페이지 49378 : https://jumpit.saramin.co.kr/position/49377
상세 페이지 49648 : https://jumpit.saramin.co.kr/position/49647
상세 페이지 49157 : https://jumpit.saramin.co.kr/position/49156
상세 페이지 50001 : https://jumpit.saramin.co.kr/position/50000
상세 페이지 49030 : https://jumpit.saramin.co.kr/position/49029
상세 페이지 49894 : https://jumpit.saramin.co.kr/position/49893
상세 페이지 49859 : https://jumpit.saramin.co.kr/position/49858
상세 페이지 49375 : https://jumpit.saramin.co.kr/position/49374
상세 페이지 49379 : https://jumpit.saramin.co.kr/position/49378
상세 페이지 49891 : https://jumpit.saramin.co.kr/position/49890
상세 페이지 49159 : https://jumpit.saramin.co.kr/position/49158
상세 페이지 49179 : https://jumpit.saramin.co.kr/position/49178
상세 페이지 49767 : https://jumpit.saramin.co.kr/position/49766
상세 페이지 49584 : https://jumpit.saramin.co.kr/position/49583
상세 페이지 49866 : https://jumpit.saramin.co.kr/position/49865
상세 페이지 49317 : https://jumpit.saramin.co.kr/position/49316
상세 페이지 49310 : https://jumpit.saramin.co.kr/position/49309
상세 페이지 49712 : https://jumpit.saramin.co.kr/position/49711
상세 페이지 48879 : https://jumpit.saramin.co.kr/position/48878
상세 페이지 50018 : https://jumpit.saramin.co.kr/position/50017
상세 페이지 49587 : https://jumpit.saramin.co.kr/position/49586
상세 페이지 49592 : https://jumpit.saramin.co.kr/position/49591
상세 페이지 31071 : https://jumpit.saramin.co.kr/position/31070
상세 페이지 49589 : https://jumpit.saramin.co.kr/position/49588
상세 페이지 49573 : https://jumpit.saramin.co.kr/position/49572
상세 페이지 49803 : https://jumpit.saramin.co.kr/position/49802
상세 페이지 49572 : https://jumpit.saramin.co.kr/position/49571
상세 페이지 49869 : https://jumpit.saramin.co.kr/position/49868
상세 페이지 49251 : https://jumpit.saramin.co.kr/position/49250
상세 페이지 49570 : https://jumpit.saramin.co.kr/position/49569
상세 페이지 49689 : https://jumpit.saramin.co.kr/position/49688
상세 페이지 49696 : https://jumpit.saramin.co.kr/position/49695
상세 페이지 12031 : https://jumpit.saramin.co.kr/position/12030
상세 페이지 49649 : https://jumpit.saramin.co.kr/position/49648
상세 페이지 49419 : https://jumpit.saramin.co.kr/position/49418
상세 페이지 49742 : https://jumpit.saramin.co.kr/position/49741
상세 페이지 48732 : https://jumpit.saramin.co.kr/position/48731
상세 페이지 50030 : https://jumpit.saramin.co.kr/position/50029
상세 페이지 50028 : https://jumpit.saramin.co.kr/position/50027
상세 페이지 49555 : https://jumpit.saramin.co.kr/position/49554
상세 페이지 49458 : https://jumpit.saramin.co.kr/position/49457
상세 페이지 50193 : https://jumpit.saramin.co.kr/position/50192
상세 페이지 49741 : https://jumpit.saramin.co.kr/position/49740
상세 페이지 48739 : https://jumpit.saramin.co.kr/position/48738
상세 페이지 49005 : https://jumpit.saramin.co.kr/position/49004
상세 페이지 49682 : https://jumpit.saramin.co.kr/position/49681
상세 페이지 49482 : https://jumpit.saramin.co.kr/position/49481
상세 페이지 49181 : https://jumpit.saramin.co.kr/position/49180
상세 페이지 50080 : https://jumpit.saramin.co.kr/position/50079
상세 페이지 49542 : https://jumpit.saramin.co.kr/position/49541
상세 페이지 50518 : https://jumpit.saramin.co.kr/position/50517
상세 페이지 49762 : https://jumpit.saramin.co.kr/position/49761
상세 페이지 50221 : https://jumpit.saramin.co.kr/position/50220
상세 페이지 50504 : https://jumpit.saramin.co.kr/position/50503
상세 페이지 49524 : https://jumpit.saramin.co.kr/position/49523
상세 페이지 49299 : https://jumpit.saramin.co.kr/position/49298
상세 페이지 49297 : https://jumpit.saramin.co.kr/position/49296
상세 페이지 49449 : https://jumpit.saramin.co.kr/position/49448
상세 페이지 50501 : https://jumpit.saramin.co.kr/position/50500
상세 페이지 48950 : https://jumpit.saramin.co.kr/position/48949
상세 페이지 49980 : https://jumpit.saramin.co.kr/position/49979
상세 페이지 50075 : https://jumpit.saramin.co.kr/position/50074
상세 페이지 49324 : https://jumpit.saramin.co.kr/position/49323
상세 페이지 50500 : https://jumpit.saramin.co.kr/position/50499
상세 페이지 49821 : https://jumpit.saramin.co.kr/position/49820
상세 페이지 49588 : https://jumpit.saramin.co.kr/position/49587
상세 페이지 50390 : https://jumpit.saramin.co.kr/position/50389
상세 페이지 49148 : https://jumpit.saramin.co.kr/position/49147
상세 페이지 49590 : https://jumpit.saramin.co.kr/position/49589
상세 페이지 49973 : https://jumpit.saramin.co.kr/position/49972
상세 페이지 49531 : https://jumpit.saramin.co.kr/position/49530
상세 페이지 49768 : https://jumpit.saramin.co.kr/position/49767
상세 페이지 50039 : https://jumpit.saramin.co.kr/position/50038
상세 페이지 49586 : https://jumpit.saramin.co.kr/position/49585
상세 페이지 50037 : https://jumpit.saramin.co.kr/position/50036
상세 페이지 50006 : https://jumpit.saramin.co.kr/position/50005
상세 페이지 48709 : https://jumpit.saramin.co.kr/position/48708
상세 페이지 48708 : https://jumpit.saramin.co.kr/position/48707
상세 페이지 49500 : https://jumpit.saramin.co.kr/position/49499
상세 페이지 49650 : https://jumpit.saramin.co.kr/position/49649
상세 페이지 48722 : https://jumpit.saramin.co.kr/position/48721
상세 페이지 49131 : https://jumpit.saramin.co.kr/position/49130
상세 페이지 48733 : https://jumpit.saramin.co.kr/position/48732
상세 페이지 50122 : https://jumpit.saramin.co.kr/position/50121
상세 페이지 50272 : https://jumpit.saramin.co.kr/position/50271
상세 페이지 50304 : https://jumpit.saramin.co.kr/position/50303
상세 페이지 50419 : https://jumpit.saramin.co.kr/position/50418
상세 페이지 50491 : https://jumpit.saramin.co.kr/position/50490
상세 페이지 49177 : https://jumpit.saramin.co.kr/position/49176
상세 페이지 48740 : https://jumpit.saramin.co.kr/position/48739
상세 페이지 50191 : https://jumpit.saramin.co.kr/position/50190
상세 페이지 50487 : https://jumpit.saramin.co.kr/position/50486
상세 페이지 49180 : https://jumpit.saramin.co.kr/position/49179
상세 페이지 48834 : https://jumpit.saramin.co.kr/position/48833
상세 페이지 50155 : https://jumpit.saramin.co.kr/position/50154
상세 페이지 49893 : https://jumpit.saramin.co.kr/position/49892
상세 페이지 49975 : https://jumpit.saramin.co.kr/position/49974
상세 페이지 49053 : https://jumpit.saramin.co.kr/position/49052
상세 페이지 48843 : https://jumpit.saramin.co.kr/position/48842
상세 페이지 49417 : https://jumpit.saramin.co.kr/position/49416
상세 페이지 49603 : https://jumpit.saramin.co.kr/position/49602
상세 페이지 49716 : https://jumpit.saramin.co.kr/position/49715
상세 페이지 48878 : https://jumpit.saramin.co.kr/position/48877
상세 페이지 49715 : https://jumpit.saramin.co.kr/position/49714
상세 페이지 49943 : https://jumpit.saramin.co.kr/position/49942
상세 페이지 49178 : https://jumpit.saramin.co.kr/position/49177
상세 페이지 50576 : https://jumpit.saramin.co.kr/position/50575
상세 페이지 50361 : https://jumpit.saramin.co.kr/position/50360
상세 페이지 49544 : https://jumpit.saramin.co.kr/position/49543
상세 페이지 50573 : https://jumpit.saramin.co.kr/position/50572
상세 페이지 49051 : https://jumpit.saramin.co.kr/position/49050
상세 페이지 50167 : https://jumpit.saramin.co.kr/position/50166
상세 페이지 48979 : https://jumpit.saramin.co.kr/position/48978
상세 페이지 49848 : https://jumpit.saramin.co.kr/position/49847
상세 페이지 49261 : https://jumpit.saramin.co.kr/position/49260
상세 페이지 49459 : https://jumpit.saramin.co.kr/position/49458
상세 페이지 49268 : https://jumpit.saramin.co.kr/position/49267
상세 페이지 49690 : https://jumpit.saramin.co.kr/position/49689
상세 페이지 49546 : https://jumpit.saramin.co.kr/position/49545
상세 페이지 49456 : https://jumpit.saramin.co.kr/position/49455
상세 페이지 49562 : https://jumpit.saramin.co.kr/position/49561
상세 페이지 49842 : https://jumpit.saramin.co.kr/position/49841
상세 페이지 49728 : https://jumpit.saramin.co.kr/position/49727
상세 페이지 50081 : https://jumpit.saramin.co.kr/position/50080
상세 페이지 49847 : https://jumpit.saramin.co.kr/position/49846
상세 페이지 48883 : https://jumpit.saramin.co.kr/position/48882
상세 페이지 49348 : https://jumpit.saramin.co.kr/position/49347
상세 페이지 49420 : https://jumpit.saramin.co.kr/position/49419
상세 페이지 50029 : https://jumpit.saramin.co.kr/position/50028
상세 페이지 46045 : https://jumpit.saramin.co.kr/position/46044
상세 페이지 49867 : https://jumpit.saramin.co.kr/position/49866
상세 페이지 48884 : https://jumpit.saramin.co.kr/position/48883
상세 페이지 50189 : https://jumpit.saramin.co.kr/position/50188
상세 페이지 49897 : https://jumpit.saramin.co.kr/position/49896
상세 페이지 50015 : https://jumpit.saramin.co.kr/position/50014
상세 페이지 48956 : https://jumpit.saramin.co.kr/position/48955
상세 페이지 49974 : https://jumpit.saramin.co.kr/position/49973
상세 페이지 49325 : https://jumpit.saramin.co.kr/position/49324
상세 페이지 49754 : https://jumpit.saramin.co.kr/position/49753
상세 페이지 49127 : https://jumpit.saramin.co.kr/position/49126
상세 페이지 49298 : https://jumpit.saramin.co.kr/position/49297
상세 페이지 49129 : https://jumpit.saramin.co.kr/position/49128
상세 페이지 50357 : https://jumpit.saramin.co.kr/position/50356
상세 페이지 50356 : https://jumpit.saramin.co.kr/position/50355
상세 페이지 49942 : https://jumpit.saramin.co.kr/position/49941
상세 페이지 50392 : https://jumpit.saramin.co.kr/position/50391
상세 페이지 50503 : https://jumpit.saramin.co.kr/position/50502
상세 페이지 50162 : https://jumpit.saramin.co.kr/position/50161
상세 페이지 49042 : https://jumpit.saramin.co.kr/position/49041
상세 페이지 49673 : https://jumpit.saramin.co.kr/position/49672
상세 페이지 49097 : https://jumpit.saramin.co.kr/position/49096
상세 페이지 49519 : https://jumpit.saramin.co.kr/position/49518
상세 페이지 49518 : https://jumpit.saramin.co.kr/position/49517
상세 페이지 49763 : https://jumpit.saramin.co.kr/position/49762
상세 페이지 50354 : https://jumpit.saramin.co.kr/position/50353
상세 페이지 50569 : https://jumpit.saramin.co.kr/position/50568
상세 페이지 49517 : https://jumpit.saramin.co.kr/position/49516
상세 페이지 50342 : https://jumpit.saramin.co.kr/position/50341
상세 페이지 50571 : https://jumpit.saramin.co.kr/position/50570
상세 페이지 50278 : https://jumpit.saramin.co.kr/position/50277
상세 페이지 50157 : https://jumpit.saramin.co.kr/position/50156
상세 페이지 49195 : https://jumpit.saramin.co.kr/position/49194
상세 페이지 49697 : https://jumpit.saramin.co.kr/position/49696
상세 페이지 49196 : https://jumpit.saramin.co.kr/position/49195
상세 페이지 48490 : https://jumpit.saramin.co.kr/position/48489
상세 페이지 48951 : https://jumpit.saramin.co.kr/position/48950
상세 페이지 49171 : https://jumpit.saramin.co.kr/position/49170
상세 페이지 49172 : https://jumpit.saramin.co.kr/position/49171
상세 페이지 49448 : https://jumpit.saramin.co.kr/position/49447
상세 페이지 49491 : https://jumpit.saramin.co.kr/position/49490
상세 페이지 49194 : https://jumpit.saramin.co.kr/position/49193
상세 페이지 48945 : https://jumpit.saramin.co.kr/position/48944
상세 페이지 48946 : https://jumpit.saramin.co.kr/position/48945
상세 페이지 48693 : https://jumpit.saramin.co.kr/position/48692
상세 페이지 49213 : https://jumpit.saramin.co.kr/position/49212
상세 페이지 49409 : https://jumpit.saramin.co.kr/position/49408
상세 페이지 49743 : https://jumpit.saramin.co.kr/position/49742
상세 페이지 49212 : https://jumpit.saramin.co.kr/position/49211
상세 페이지 49457 : https://jumpit.saramin.co.kr/position/49456
상세 페이지 50359 : https://jumpit.saramin.co.kr/position/50358
상세 페이지 50166 : https://jumpit.saramin.co.kr/position/50165
상세 페이지 48887 : https://jumpit.saramin.co.kr/position/48886
상세 페이지 50185 : https://jumpit.saramin.co.kr/position/50184
상세 페이지 49228 : https://jumpit.saramin.co.kr/position/49227
상세 페이지 50082 : https://jumpit.saramin.co.kr/position/50081
상세 페이지 49372 : https://jumpit.saramin.co.kr/position/49371
상세 페이지 50313 : https://jumpit.saramin.co.kr/position/50312
상세 페이지 49304 : https://jumpit.saramin.co.kr/position/49303
상세 페이지 49671 : https://jumpit.saramin.co.kr/position/49670
상세 페이지 49782 : https://jumpit.saramin.co.kr/position/49781
상세 페이지 49369 : https://jumpit.saramin.co.kr/position/49368
상세 페이지 49659 : https://jumpit.saramin.co.kr/position/49658
상세 페이지 49641 : https://jumpit.saramin.co.kr/position/49640
상세 페이지 49526 : https://jumpit.saramin.co.kr/position/49525
상세 페이지 49825 : https://jumpit.saramin.co.kr/position/49824
상세 페이지 49300 : https://jumpit.saramin.co.kr/position/49299
상세 페이지 49591 : https://jumpit.saramin.co.kr/position/49590
상세 페이지 49382 : https://jumpit.saramin.co.kr/position/49381
상세 페이지 49128 : https://jumpit.saramin.co.kr/position/49127
상세 페이지 49184 : https://jumpit.saramin.co.kr/position/49183
상세 페이지 50190 : https://jumpit.saramin.co.kr/position/50189
상세 페이지 50031 : https://jumpit.saramin.co.kr/position/50030
상세 페이지 49331 : https://jumpit.saramin.co.kr/position/49330
상세 페이지 50008 : https://jumpit.saramin.co.kr/position/50007
상세 페이지 49125 : https://jumpit.saramin.co.kr/position/49124
상세 페이지 49529 : https://jumpit.saramin.co.kr/position/49528
상세 페이지 49896 : https://jumpit.saramin.co.kr/position/49895
상세 페이지 50430 : https://jumpit.saramin.co.kr/position/50429
상세 페이지 49994 : https://jumpit.saramin.co.kr/position/49993
상세 페이지 50130 : https://jumpit.saramin.co.kr/position/50129
상세 페이지 50159 : https://jumpit.saramin.co.kr/position/50158
상세 페이지 50358 : https://jumpit.saramin.co.kr/position/50357
상세 페이지 48738 : https://jumpit.saramin.co.kr/position/48737
상세 페이지 49312 : https://jumpit.saramin.co.kr/position/49311
상세 페이지 50181 : https://jumpit.saramin.co.kr/position/50180
상세 페이지 49543 : https://jumpit.saramin.co.kr/position/49542
상세 페이지 49052 : https://jumpit.saramin.co.kr/position/49051
상세 페이지 49476 : https://jumpit.saramin.co.kr/position/49475
상세 페이지 49599 : https://jumpit.saramin.co.kr/position/49598
상세 페이지 49598 : https://jumpit.saramin.co.kr/position/49597
상세 페이지 49427 : https://jumpit.saramin.co.kr/position/49426
상세 페이지 48949 : https://jumpit.saramin.co.kr/position/48948
상세 페이지 49323 : https://jumpit.saramin.co.kr/position/49322
상세 페이지 49944 : https://jumpit.saramin.co.kr/position/49943
상세 페이지 50019 : https://jumpit.saramin.co.kr/position/50018
상세 페이지 49816 : https://jumpit.saramin.co.kr/position/49815
상세 페이지 49907 : https://jumpit.saramin.co.kr/position/49906
상세 페이지 48694 : https://jumpit.saramin.co.kr/position/48693
상세 페이지 47305 : https://jumpit.saramin.co.kr/position/47304
상세 페이지 50574 : https://jumpit.saramin.co.kr/position/50573
상세 페이지 50199 : https://jumpit.saramin.co.kr/position/50198
상세 페이지 48868 : https://jumpit.saramin.co.kr/position/48867
상세 페이지 48943 : https://jumpit.saramin.co.kr/position/48942
상세 페이지 49414 : https://jumpit.saramin.co.kr/position/49413
상세 페이지 49525 : https://jumpit.saramin.co.kr/position/49524
상세 페이지 48839 : https://jumpit.saramin.co.kr/position/48838
상세 페이지 49527 : https://jumpit.saramin.co.kr/position/49526
상세 페이지 49072 : https://jumpit.saramin.co.kr/position/49071
상세 페이지 48838 : https://jumpit.saramin.co.kr/position/48837
상세 페이지 50168 : https://jumpit.saramin.co.kr/position/50167
상세 페이지 49415 : https://jumpit.saramin.co.kr/position/49414
상세 페이지 49264 : https://jumpit.saramin.co.kr/position/49263
상세 페이지 50417 : https://jumpit.saramin.co.kr/position/50416
상세 페이지 48948 : https://jumpit.saramin.co.kr/position/48947
상세 페이지 50291 : https://jumpit.saramin.co.kr/position/50290
상세 페이지 50563 : https://jumpit.saramin.co.kr/position/50562
상세 페이지 49377 : https://jumpit.saramin.co.kr/position/49376
상세 페이지 48881 : https://jumpit.saramin.co.kr/position/48880
상세 페이지 48934 : https://jumpit.saramin.co.kr/position/48933
상세 페이지 49616 : https://jumpit.saramin.co.kr/position/49615
상세 페이지 49454 : https://jumpit.saramin.co.kr/position/49453
상세 페이지 49596 : https://jumpit.saramin.co.kr/position/49595
상세 페이지 49597 : https://jumpit.saramin.co.kr/position/49596
상세 페이지 48524 : https://jumpit.saramin.co.kr/position/48523
상세 페이지 49567 : https://jumpit.saramin.co.kr/position/49566
상세 페이지 49260 : https://jumpit.saramin.co.kr/position/49259
상세 페이지 50182 : https://jumpit.saramin.co.kr/position/50181
상세 페이지 48832 : https://jumpit.saramin.co.kr/position/48831
상세 페이지 49795 : https://jumpit.saramin.co.kr/position/49794
상세 페이지 50121 : https://jumpit.saramin.co.kr/position/50120
상세 페이지 49029 : https://jumpit.saramin.co.kr/position/49028
상세 페이지 49447 : https://jumpit.saramin.co.kr/position/49446
상세 페이지 49530 : https://jumpit.saramin.co.kr/position/49529
상세 페이지 49418 : https://jumpit.saramin.co.kr/position/49417
상세 페이지 49026 : https://jumpit.saramin.co.kr/position/49025
상세 페이지 49357 : https://jumpit.saramin.co.kr/position/49356
상세 페이지 49138 : https://jumpit.saramin.co.kr/position/49137
상세 페이지 49014 : https://jumpit.saramin.co.kr/position/49013
상세 페이지 49321 : https://jumpit.saramin.co.kr/position/49320
상세 페이지 49477 : https://jumpit.saramin.co.kr/position/49476
상세 페이지 49428 : https://jumpit.saramin.co.kr/position/49427
상세 페이지 49100 : https://jumpit.saramin.co.kr/position/49099

In [3]:
detailDataFrame = pd.DataFrame(data)

In [4]:
detailDataFrame

,title,company,pride,techStack,mainWork,requirements,preferential,welfare,procedures,career,education,closedAt,jobLocation
0,서버개발팀 모바일 개발자(경력),사이버다임,"[🚆2호선 역세권 기업, #유연근무제, #도서구입비지원]","[Android Studio, Node.js, Webpack, Redux, Reac...","[• 자사 솔루션 모바일 개발, - Destiny ECM(데스티니 ECM)은 고객사...","[• 관련 경력을 5년 이상 보유한 분, • React Native 개발이 가능한 ...","[• 채팅 클라이언트 개발 경험이 있으신 분, • 기업용 솔루션 개발 경험이 있으신...","[직원 중심의 조직문화를 만들어갑니다., 유연근무제와 자유로운 연차 사용으로 일과 ...",[• 서류전형 → 1차 면접 → 2차 면접 (필요 시) → 입사 협의],경력 5~15년,"대학졸업(2,3년) 이상",2025년 05월 24일,"서울 송파구 올림픽로 299, 12층지도보기·주소복사"
1,AI연구팀장 경력10년이상,아이스크림아트,[🚆2호선 역세권 기업],"[AI/인공지능, MySQL, REST API, React, Flow, Node.j...","[ㆍ AI(ML/DL/컴퓨터비전) 기술 개발, ㆍ AI기반연구팀 관리 업무]","[[ 자격요건 ], ㆍ4년제 학사 이상, ㆍ전공 : 컴퓨터 공학, 전자 공학 관련 ...","[ㆍ컴퓨터 공학 관련 학위 (석사/박사) 소지자, ㆍ논문 발표 또는 컴퓨터비전/AI...","[워라밸 근무시간제도 - 자율 출퇴근(8~10시), 정기 종합건강 검진비 지원 - ...","[ㆍ 이력서, 자기소개서 제출, ㆍ 공인시험 및 기타 자격증 사본 제출 (소지자 한...",경력 10~15년,무관,2025년 05월 16일,"서울 강남구 테헤란로 512, 18층 (대치동,신안빌딩)지도보기·주소복사"
2,BE Engineer,이마고웍스,"[🚆3호선 역세권 기업, 💰시리즈B 투자유치, #반바지/슬리퍼 OK, #수평적조직,...","[MongoDB, TypeScript, Rust, NoSql, AWS, NestJS...","[• 각 포지션의 기술을 바탕으로 Dentbird Solutions 제품화, • 솔...","[• 주도적으로 문제를 해결하는 능력이 뛰어나신 분, • 자유롭게 토론하고 의견을 ...","[• 개발환경, 프로그래밍 언어에 제한 없이 다양한 환경 및 언어를 편하게 하실 수...","[직원이 편해야 회사가 잘된다!, • 수평적인 조직 문화, • 자율 출퇴근제 운영,...","[*서류 심사 - 1차 면접 - 2차 면접 - 입사 제안 , *필요한 경우 지원...",경력 5~8년,대학교졸업(4년) 이상,2025년 05월 11일,"서울 강남구 강남대로 636 1층, 2층 (신사동, 두원빌딩)지도보기·주소복사"
3,신입 개발자 채용,하이퍼에픽,"[🚆9호선 역세권 기업, 🏢코퍼스코리아 계열사]","[Git, Kotlin, TypeScript, Spring Boot, Node.js...","[• 어플리케이션 백엔드 서버 개발 및 유지보수, • 관련 부서와 긴밀하게 협업하면...","[• spring boot, kotlin 경험이 있는 분, • postgresq...","[• type script 경험이 있는 분, • nodejs 경험이 있는 분]","[• 퇴직금, • 4대보험, • 간식 제공, • 자율 복장, • 수평적 조...","[[근무환경], • 고용형태 : 정규직, • 근무지역 : 서울 강남구, • 급여조건...",신입~2년,무관,2025년 05월 16일,"서울 강남구 강남대로 484, 602호 (논현동,99빌딩)지도보기·주소복사"
4,Solution Developer,이마고웍스,"[🚆3호선 역세권 기업, 💰시리즈B 투자유치, #반바지/슬리퍼 OK, #수평적조직,...","[Figma, Confluence, Jira]","[• 3D 의료용 소프트웨어 개발 , • AI, CAD 라이브러리 적용을 통한 치과...","[• 프로그래밍 능숙자, • 소프트웨어 제품화가 가능하신 분, • 경력 3년 이상,...","[• 디자인 패턴 등 아키텍처 설계/구현에 능숙하신 분, • CMake 등 빌드 시...","[직원이 편해야 회사가 잘된다!, • 수평적인 조직 문화, • 자율 출퇴근제 운영,...","[*채용 절차 : 서류 심사 - 1차 면접 - 2차 면접 - 입사 확정, ﻿*필요한...",경력 3~6년,대학교졸업(4년) 이상,2025년 05월 18일,"서울 강남구 강남대로 636 1층, 2층 (신사동, 두원빌딩)지도보기·주소복사"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1422,생성형 AI 기반 통합 문서비서 솔루션 CTO,한국통신데이터,[],"[React, AWS, NestJS]","[• 생성형 AI 기반 문서 자동화 플랫폼 설계 및 총괄 개발, • FastAPI,...","[• 경력 : 경력 5년 이상, • Python 또는 Typescript 기반 실무...","[• LangChain / LlamaIndex 등 실제 RAG 구현 경험, • Qd...","[• 비대면 근무 가능 (조율), • 사내카페 보유, • 업무장비 및 사무기기 지원]","[[채용절차], • 서류전형 → 온라인 코딩테스트 → 1차 인터뷰 → 처우 협의 →...",경력 5~10년,"대학졸업(2,3년) 이상",2025년 05월 19일,경남 진주시 대신로244번길 8 205호지도보기·주소복사
1423,소프트웨어개발자 경력자 채용,라온솔루션,[],"[AI/인공지능, C++, SW, Embedded Linux, Embedded, C...","[• Windows Application개발, • 네트워크 통신 Applicatio...","[• 경력 : 2년 이상, • 사용언어: C/C++, C# 중급 2개 이상 사용 ...","[• 컴퓨터/시스템공학, • Embedded Linux 개발 가능자, • 이미지프로...","[• 건강보험, 고용보험, 국민연금, 산재보험, • 퇴직연금, 연차제도, 워크샵/M...",[],경력 2~20년,대학교졸업(4년) 이상,2025년 06월 06일,충북 청주시 청원구 오창읍 양청송대길 10 303호 청주미래누리터(지식산업센터)지도...
1424,앱 개발자 경력 채용 (6~9년),텐빌리언,[],"[Android OS, REST API, React, iOS, Flutter]","[• 앱스토어 배포 및 출시, • 어플리케이션 개발, • 어플리케이션 기능 구현,...","[• 경력 6~9년, • 구글플레이 및 애플 앱스토어에 앱 배포 및 출시 가능자, ...","[• Android 개발 이해도 우수자, • iOS Native 개발 이해도 우수자]","[-자유로운 환경의 업무 스타일, -자유로운 연차 사용 및 시차 출퇴근, -생일 연...",[서류전형-면접-합격],경력 6~9년,대학교졸업(4년) 이상,2025년 06월 02일,서울 구로구 구로동 1127-26지도보기·주소복사
1425,하드웨어 및 펌웨어 개발자,한솔리드텍,[#전공우대],"[C++, Linux, C]","[담당업무, , ㆍ하드 웨어 회로설계 (ORCAD), , ㆍSTM32 및 리눅스 펌...","[자격요건, , ㆍ학력 : 초대졸이상 (이공계 전공자), , ㆍ경력 : 경력 3~5년]","[우대사항, , ㆍ공학계열 전공자 (전공 : 전기·전자공학), , ㆍ해당 분야 경력...","[• 식사제공, 4대보험, 퇴직연금, 워크샵, 장기근속자 포상, 성과급, 각종 경조...","[전형절차, , ㆍ서류전형 > 면접 > 최종합격, , ㆍ면접일정은 추후 통보됩니다....",경력 3~5년,"대학졸업(2,3년) 이상",2025년 06월 07일,"경기도 의왕시 성고개로 53, A902호지도보기·주소복사"
1426,NPU 컴파일러 개발 엔지니어,아티크론,[🚆1호선 역세권 기업],"[C++, Linux, TensorFlow, Python, PyTorch, C]","[• ONNX, TensorFlow, PyTorch 등의 AI Model을 NPU...","[• 컴파일러 개발 경험 (front-end, back-end, optimizati...","[• TVM, Glow 등의 딥러닝 컴파일러 프레임워크를 이용한 NPU 또는 가속기...","[• 자율 출퇴근, • 연차, 반차, 육아휴직, 경조휴가, • 명절 선물, 생일 ...",[],신입,대학교졸업(4년) 이상(졸업예정자 가능),2025년 06월 08일,"서울 동대문구 경희대로 26, 311호 (회기동,삼의원창업센터)지도보기·주소복사"

In [5]:
toJsonFile(detailDataFrame, 20250510, 'Detail')

In [6]:
detailDataFrame = pd.read_json('../Data_Files/Crawling_DataFile_DetailPage_json_20250510.txt')

In [7]:

detailDataFrame.head(5)

,title,company,pride,techStack,mainWork,requirements,preferential,welfare,procedures,career,education,closedAt,jobLocation,date
0,서버개발팀 모바일 개발자(경력),사이버다임,"[🚆2호선 역세권 기업, #유연근무제, #도서구입비지원]","[Android Studio, Node.js, Webpack, Redux, Reac...","[• 자사 솔루션 모바일 개발, - Destiny ECM(데스티니 ECM)은 고객사...","[• 관련 경력을 5년 이상 보유한 분, • React Native 개발이 가능한 ...","[• 채팅 클라이언트 개발 경험이 있으신 분, • 기업용 솔루션 개발 경험이 있으신...","[직원 중심의 조직문화를 만들어갑니다., 유연근무제와 자유로운 연차 사용으로 일과 ...",[• 서류전형 → 1차 면접 → 2차 면접 (필요 시) → 입사 협의],경력 5~15년,"대학졸업(2,3년) 이상",2025년 05월 24일,"서울 송파구 올림픽로 299, 12층지도보기·주소복사",2025년-05월-10일
1,AI연구팀장 경력10년이상,아이스크림아트,[🚆2호선 역세권 기업],"[AI/인공지능, MySQL, REST API, React, Flow, Node.j...","[ㆍ AI(ML/DL/컴퓨터비전) 기술 개발, ㆍ AI기반연구팀 관리 업무]","[[ 자격요건 ], ㆍ4년제 학사 이상, ㆍ전공 : 컴퓨터 공학, 전자 공학 관련 ...","[ㆍ컴퓨터 공학 관련 학위 (석사/박사) 소지자, ㆍ논문 발표 또는 컴퓨터비전/AI...","[워라밸 근무시간제도 - 자율 출퇴근(8~10시), 정기 종합건강 검진비 지원 - ...","[ㆍ 이력서, 자기소개서 제출, ㆍ 공인시험 및 기타 자격증 사본 제출 (소지자 한...",경력 10~15년,무관,2025년 05월 16일,"서울 강남구 테헤란로 512, 18층 (대치동,신안빌딩)지도보기·주소복사",2025년-05월-10일
2,BE Engineer,이마고웍스,"[🚆3호선 역세권 기업, 💰시리즈B 투자유치, #반바지/슬리퍼 OK, #수평적조직,...","[MongoDB, TypeScript, Rust, NoSql, AWS, NestJS...","[• 각 포지션의 기술을 바탕으로 Dentbird Solutions 제품화, • 솔...","[• 주도적으로 문제를 해결하는 능력이 뛰어나신 분, • 자유롭게 토론하고 의견을 ...","[• 개발환경, 프로그래밍 언어에 제한 없이 다양한 환경 및 언어를 편하게 하실 수...","[직원이 편해야 회사가 잘된다!, • 수평적인 조직 문화, • 자율 출퇴근제 운영,...","[*서류 심사 - 1차 면접 - 2차 면접 - 입사 제안 , *필요한 경우 지원...",경력 5~8년,대학교졸업(4년) 이상,2025년 05월 11일,"서울 강남구 강남대로 636 1층, 2층 (신사동, 두원빌딩)지도보기·주소복사",2025년-05월-10일
3,신입 개발자 채용,하이퍼에픽,"[🚆9호선 역세권 기업, 🏢코퍼스코리아 계열사]","[Git, Kotlin, TypeScript, Spring Boot, Node.js...","[• 어플리케이션 백엔드 서버 개발 및 유지보수, • 관련 부서와 긴밀하게 협업하면...","[• spring boot, kotlin 경험이 있는 분, • postgresq...","[• type script 경험이 있는 분, • nodejs 경험이 있는 분]","[• 퇴직금, • 4대보험, • 간식 제공, • 자율 복장, • 수평적 조...","[[근무환경], • 고용형태 : 정규직, • 근무지역 : 서울 강남구, • 급여조건...",신입~2년,무관,2025년 05월 16일,"서울 강남구 강남대로 484, 602호 (논현동,99빌딩)지도보기·주소복사",2025년-05월-10일
4,Solution Developer,이마고웍스,"[🚆3호선 역세권 기업, 💰시리즈B 투자유치, #반바지/슬리퍼 OK, #수평적조직,...","[Figma, Confluence, Jira]","[• 3D 의료용 소프트웨어 개발 , • AI, CAD 라이브러리 적용을 통한 치과...","[• 프로그래밍 능숙자, • 소프트웨어 제품화가 가능하신 분, • 경력 3년 이상,...","[• 디자인 패턴 등 아키텍처 설계/구현에 능숙하신 분, • CMake 등 빌드 시...","[직원이 편해야 회사가 잘된다!, • 수평적인 조직 문화, • 자율 출퇴근제 운영,...","[*채용 절차 : 서류 심사 - 1차 면접 - 2차 면접 - 입사 확정, ﻿*필요한...",경력 3~6년,대학교졸업(4년) 이상,2025년 05월 18일,"서울 강남구 강남대로 636 1층, 2층 (신사동, 두원빌딩)지도보기·주소복사",2025년-05월-10일